### ISSUE TITLE
Error : Could not reservate ticket

### ISSUE THREAD

**Issue by blamejonas** [Ecostack/TicketSwapper#2]
Normally it just says no tickets but after a while it kept saying : could not reservate ticket NO_TICKETS_COULD_BE_RESERVED
Is this normal ? Or an error

**Comment by Ecostack** [comment]
I have the feeling that ticket swap implemented a check against automated usage of their system. It used to work last year in October and not, it seems, they block the bot.

I think, if someone modifies how the bot operates, it might be possible to mitigate their bot detection.

**Comment by blamejonas** [comment]
Yeah im not to sure. I had it running for 5hours yesterday with no issues. Today I tried it with cluster mode on. Maybe that's what caused it

**Comment by Ecostack** [comment]
Is this still happening?

**Comment by blamejonas** [comment]
everything is perfect , thank you. Forgot to close it
