### ISSUE TITLE
Issues with getting weekend tickets 

### ISSUE THREAD

**Issue by failcfx** [Ecostack/TicketSwapper#3]
I'm trying to get tickets for a festival that's all weekend. But i'm trying to get a Sunday ticket specifically. But no matter what URL I copy and paste it only catches me Saturday tickets for some reason

Is there something i can try to fix that issue?

**Comment by Ecostack** [comment]
Have you tried to use the URL which is specifically for the event with the Sunday tickets?

**Comment by Ecostack** [comment]
If that does not work, then the code has to be modified to accept a parameter that would address that issue.

**Comment by failcfx** [comment]
Yeah the URL thing doesn't work. And is there any chance you could help me with that or show me how to modify that. I don't have a lot experience with this

**Comment by Defmatt792** [comment]
Hi, I have the exact same problem. I would like to get 3-days tickets for a festival, but I can only get tickets for the first day of the festival - not the 3-days tickets. The problem remains even if I use the URL specifically for the 3-days tickets. Has anyone found a solution?

**Comment by failcfx** [comment]
I'm not sure if this is a working solution. But I tried changing "Referer" and "Origin" in the file request.ts. To the exact URL of the event that I want. But haven't seen anything that confirms that it was fixed by doing that. I was hoping ecostack would reply to what file we would have to modify

**Comment by Defmatt792** [comment]
All right. I know nothing about programming, so I hope that you could help us Ecostack... :-)

**Comment by Ecostack** [comment]
Do you have an event which has two or more ticket choices?

**Comment by Defmatt792** [comment]
Exactly, and I can only get the first ticket choice, even if I use the URL of another ticket choice...

**Comment by Ecostack** [comment]
Just published version 1.0.4. The command line options have changed now

-t <TOKEN> -u <EVENT_URL> [-o <TICKET_OPTION_1_OR_HIGHER>] [-c <CLUSTER_MODE>]

**Comment by Defmatt792** [comment]
Thank you so much! I will try it and let you know if it works!

**Comment by failcfx** [comment]
Thank you ! so for example : 

-t -u https://www.ticketswap.nl/event/dgtl-amsterdam-2020/997741b5-b864-4bfd-a2ff-b3db63552e47 [-o 2] [-ce true]. So I dont need the exact URL now just the overal URL with the ticket option. corrrect?

**Comment by Ecostack** [comment]
-t TOKEN_HERE -u EVENT_URL -o 2

That would be it.

**Comment by failcfx** [comment]
I get this error code : Could not reservate ticket. undefined Authentication needed to access this field. 

using : 

ticketswapper -t ZTEzYWU5ODA2OGUyMzcyNDFhMGQxYWRlMjJjZjU0ZThmNTU2NzYyMmU3NDkzYzdhOGMxNzIzZjlmY2JlZDA3Ng -u https://www.ticketswap.nl/event/dgtl-amsterdam-2020/saturday-tickets/997741b5-b864-4bfd-a2ff-b3db63552e47/1540019 -o 2

**Comment by Ecostack** [comment]
Have you tried buying a ticket one the website itself with your current token?

**Comment by failcfx** [comment]
ohh I see why it gave me that error. No I just wanted to give it a test run on a event that has tickets available to see if it would work choosing different days

**Comment by failcfx** [comment]
yes is that not the right token?

**Comment by failcfx** [comment]
Not sure what I did wrong. I still get the same error code

**Comment by failcfx** [comment]
buying a ticket manually works fine with my current token . if thats what you meant

**Comment by Defmatt792** [comment]
Hi again, I have the same problem as failcfx, I get: 'Could not reservate ticket.' undefined 'Authentication needed to access this field'

**Comment by failcfx** [comment]
Yeah strange. Everything works fine until it has to reservate the ticket. we'll have to wait for ecostack again. Sorry for all the trouble ecostack. When it is fixed, ill be sure to donate something for your time if you want

**Comment by supa17** [comment]
oh im glad im not the only one having this issue. Any updates yet?

**Comment by supa17** [comment]
is there a way for me to go back to the older version until this one has a fix?

**Comment by dguyonvarch** [comment]
I submit a [PR](https://github.com/Ecostack/TicketSwapper/pull/4) that fix the `Authentication needed to access this field`
It works for me :muscle:

**Comment by supa17** [comment]
good stuff! how do I apply this?

**Comment by Ecostack** [comment]
PR was accepted and new version is publish on npm. Check it out!

**Comment by Defmatt792** [comment]
It works perfectly well! Thank you so much!

**Comment by Ecostack** [comment]
Nice, I will close the issue then!
